name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install tree && tree -d $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE && ls -la
  npm-path-win:
    runs-on: windows-latest
    steps:
      - run: npm config get prefix
      - run: cd C:\npm\prefix;ls
  npm-path-mac:
    runs-on: macos-latest
    steps:
      - run: npm config get prefix
      - run: cd /usr/local && ls -la
  npm-path-lin:
    runs-on: ubuntu-latest
    steps:
      - run: npm config get prefix
      - run: cd /usr/local && ls -la
