name: Deploy

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: akhileshns/ga-demo@master
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt -y install tree && tree -d $GITHUB_WORKSPACE
      - run: cd $GITHUB_WORKSPACE && ls -la
  npm-path-win:
    runs-on: windows-latest
    steps:
      - run: npm config get prefix
      - run: cd C:\npm\prefix;ls
      - run: C:\npm\prefix\yarn.cmd --version
  npm-path-mac:
    runs-on: macos-latest
    steps:
      - run: npm config get prefix
      - run: cd /usr/local/bin && ls -la
      - run: /usr/local/bin/npm --version
  npm-path-lin:
    runs-on: ubuntu-latest
    steps:
      - run: npm config get prefix
      - run: cd /usr/local/bin && ls -la
      - run: /usr/local/bin/npm --version
